
from django.core.management.base import BaseCommand
from django.db.models import get_model
from decimal import Decimal

Supplier = get_model('suppliers', 'Supplier')
Product = get_model('products', 'Product')
SupplierProduct = get_model('products', 'SupplierProduct')
DeliveryCharge = get_model('freight', 'DeliveryCharge')
RemoteDeliveryCharge = get_model('freight', 'RemoteDeliveryCharge')
RemotePostcode = get_model('freight', 'RemotePostcode')
Currency = get_model('payments', 'Currency')
Installation = get_model('core', 'Installation')

class Command(BaseCommand):
    def handle(self, *args, **options):

        EMAIL = 'nam@kogan.com.au'

        email_name = EMAIL.split('@')[0].split('+')[0]
        email_domain = EMAIL.split('@')[1]

        supplier_list = [
            {
                'name': 'KHALPHA',
                'email': email_name + '+alpha@' + email_domain,
                'colour': '#990099',
            },
            {
                'name': 'KHBRAVO',
                'email': email_name + '+bravo@' + email_domain,
                'colour': '#0099CC',
            },
            {
                'name': 'KHCHARLIE',
                'email': email_name + '+charlie@' + email_domain,
                'colour': '#FF9900',
            },
            {
                'name': 'KHDELTA',
                'email': email_name + '+delta@' + email_domain,
                'colour': '#99CC66',
            },
            {
                'name': 'KHECHO',
                'email': email_name + '+echo@' + email_domain,
                'colour': '#CC0000',
            },
        ]

        product_list = [
            {'code': u'KHNEWIPADWF16BLK', 'name': u'Apple New iPad (16GB, Wi Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHNEWIPADWF32BLK', 'name': u'Apple New iPad (32GB, Wi Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHC600DK1855-55250', 'name': u'Canon EOS 600D DSLR Camera Twin IS Lens Kit', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHHOYHDUV77', 'name': u'Hoya HD UV Filter - 77mm', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHSEXARCSWHT', 'name': u'Sony Ericsson Xperia arc S (White)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHBBDDSTUWHT', 'name': u'Beats by Dr. Dre - Studio (White)', 'weight': Decimal('1.400'), 'requires_serial_number': True},
            {'code': u'KHSAMNEXS', 'name': u'New Product KHSAMNEXS', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHCANIX1100', 'name': u'Canon IXUS 1100 HS (Silver)', 'weight': Decimal('1.183'), 'requires_serial_number': True},
            {'code': u'KHCAN650DBODY', 'name': u'Canon EOS 650D DSLR Camera - Body', 'weight': Decimal('1.570'), 'requires_serial_number': True},
            {'code': u'KHNIKD3200BLKBODY', 'name': u'Nikon D3200 DSLR Camera - Body', 'weight': Decimal('1.455'), 'requires_serial_number': True},
            {'code': u'KHNIKD3200BLK18-55KIT', 'name': u'Nikon D3200 DSLR Camera 18-55mm VR Lens Kit', 'weight': Decimal('1.720'), 'requires_serial_number': True},
            {'code': u'KHNAFSDX35F18G', 'name': u'Nikon AF-S DX NIKKOR 35mm f/1.8G Lens', 'weight': Decimal('0.500'), 'requires_serial_number': True},
            {'code': u'KHCANLPE8BAT', 'name': u'Canon LP-E8 Li-Ion Camera Battery (Genuine)', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KH360FIFA12', 'name': u'FIFA 12 - Xbox 360 Game', 'weight': Decimal('0.080'), 'requires_serial_number': True},
            {'code': u'KHNID90DB', 'name': u'Nikon D90 DSLR Camera - Body Only', 'weight': Decimal('1.703'), 'requires_serial_number': True},
            {'code': u'KHFOLDEE', 'name': u'Foldee iPad & Tablet Stand', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHMXM10WIFI', 'name': u'Motorola Xoom 10" - 32GB WiFi Tablet', 'weight': Decimal('1.330'), 'requires_serial_number': True},
            {'code': u'KHNID3100DK1855-55200', 'name': u'Nikon D3100 DSLR Camera Twin VR Kit', 'weight': Decimal('2.500'), 'requires_serial_number': True},
            {'code': u'KHCAN60D200K', 'name': u'Canon EOS 60D DSLR Camera Lens Kit with EF-S 18-200mm f/3.5-5.6 IS Lens', 'weight': Decimal('2.355'), 'requires_serial_number': True},
            {'code': u'KHCAN7D200K', 'name': u'Canon EOS 7D DSLR Camera Lens Kit with EF-S 18-200mm f/3.5-5.6 IS Lens', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHCAN7D85ISK', 'name': u'Canon EOS 7D DSLR Camera Lens Kit with EF-S 15-85mm f/3.5-5.6 IS USM Lens', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHCANEF2470L', 'name': u'Canon EF 24-70mm f/2.8L USM Standard Zoom Lens', 'weight': Decimal('1.250'), 'requires_serial_number': True},
            {'code': u'KHCANEF50USM', 'name': u'Canon EF 50mm f/1.4 USM Standard Lens', 'weight': Decimal('0.620'), 'requires_serial_number': True},
            {'code': u'KHCANEF70200ISII', 'name': u'Canon EF 70-200mm f/2.8L IS II USM Telephoto Zoom Lens', 'weight': Decimal('1.790'), 'requires_serial_number': True},
            {'code': u'KHCANEF105IS', 'name': u'Canon EF 24-105mm f/4L IS USM Lens', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHSGT103GG', 'name': u'Samsung Galaxy Tab 10.1 - 16GB with 3G + WiFi (Grey)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHSGT103GW', 'name': u'Samsung Galaxy Tab 10.1 - 16GB with 3G + WiFi (White)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHSGT10WFG', 'name': u'Samsung Galaxy Tab 10.1 - 16GB with WiFi (Grey)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHSGT10WFW', 'name': u'Samsung Galaxy Tab 10.1 - 16GB with WiFi (White)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHSNEXVG20B', 'name': u'Sony Nex VG20 Body', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHSNEXVG20H', 'name': u'Sony Nex VG20 & 18-200mm Zoom Lens Kit', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHTFEC10ASH', 'name': u'Felt Envelope Tablet Case - 10" (Ash)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHTFPC10ASH', 'name': u'Felt Par Avion Tablet Case - 10" (Ash)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHTFSC10CHCL', 'name': u'Felt Sleeve Tablet Case - 10" (Charcoal)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHTMC07BLK', 'name': u'Microfibre Tablet Case - 7" (Nero)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHTMC07GRN', 'name': u'Microfibre Tablet Case - 7" (Pistachio)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KWCARRY', 'name': u'Wallee iPad Carry', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWCASEB', 'name': u'Wallee iPad 2 Case (Black)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWCASET', 'name': u'Wallee iPad 2 Case (Transparent)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWCASEW', 'name': u'Wallee iPad 2 Case (White)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWGLOVE', 'name': u'Wallee iPad Glove', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWKICK', 'name': u'Wallee iPad Kick', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWMOUNTB', 'name': u'Wallee iPad Wall Mount (Black)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWMOUNTW', 'name': u'Wallee iPad Wall Mount (White)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KWPIVOT', 'name': u'Wallee iPad Pivot', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHC600DK1855', 'name': u'Canon EOS 600D DSLR Camera Lens Kit with EF-S 18-55mm IS Lens', 'weight': Decimal('1.770'), 'requires_serial_number': True},
            {'code': u'KHHTCINCSB', 'name': u'New Product KHHTCINCSB', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHHTCDESSB', 'name': u'New Product KHHTCDESSB', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHMOTATX4GB', 'name': u'New Product KHMOTATX4GB', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHC60DK1855', 'name': u'Canon EOS 60D DSLR Camera Lens Kit with EF-S 18-55mm f/3.5-5.6 IS Lens', 'weight': Decimal('1.955'), 'requires_serial_number': True},
            {'code': u'KHNAFSDX55200F456', 'name': u'Nikon AF-S DX VR Zoom-Nikkor 55-200mm f/4-5.6G IF-ED Lens', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHIPAD16B3G', 'name': u'Apple iPad 2 - 16GB Black with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHIPAD64W3G', 'name': u'Apple iPad 2 - 64GB White with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHHTCSENXLWHT', 'name': u'HTC Sensation XL (White)', 'weight': Decimal('0.420'), 'requires_serial_number': True},
            {'code': u'KHSANPRO32SD', 'name': u'SanDisk Extreme Pro - 32GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHBBDDSHDWHT', 'name': u'Beats by Dr. Dre - Solo HD (White)', 'weight': Decimal('1.400'), 'requires_serial_number': True},
            {'code': u'KHIPAD64WWIFI', 'name': u'Apple iPad 2 - 64GB White with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHSANPRO16CF', 'name': u'SanDisk Extreme Pro - 16GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHNID3100DB', 'name': u'Nikon D3100 DSLR Camera - Body Only', 'weight': Decimal('1.455'), 'requires_serial_number': True},
            {'code': u'KHNID3100DK1855', 'name': u'Nikon D3100 DSLR Camera Lens Kit with AF-S 18-55mm f3.5-5.6 G VR Lens', 'weight': Decimal('1.720'), 'requires_serial_number': True},
            {'code': u'KHCPSS100-OLD', 'name': u'OLD - Canon Powershot S100 - Black - OLD', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKD3200BLK18-55-55-200KIT', 'name': u'Nikon D3200 DSLR Camera 18-55mm & 55-200mm Twin VR Lens Kit', 'weight': Decimal('2.500'), 'requires_serial_number': True},
            {'code': u'KHCPSS100BK', 'name': u'Canon Powershot S100 (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHCPSS100SL', 'name': u'Canon Powershot S100 (Silver)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHCANPSG12', 'name': u'Canon Powershot G12 Digital Camera', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKENEL14BATT', 'name': u'Nikon EN-EL14 Li-Ion Camera Battery (Genuine)', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHC1000HSS', 'name': u'Canon IXUS 1000HS Compact Zoom Camera (Silver)', 'weight': Decimal('1.183'), 'requires_serial_number': True},
            {'code': u'KHSAN08MSD', 'name': u'SanDisk 8GB microSDHC Memory Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSAN16MSD', 'name': u'SanDisk 16GB microSDHC Memory Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANEXT08CF', 'name': u'SanDisk Extreme - 8GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHLTHRIPADCASEWKB', 'name': u'Leather iPad Case with Bluetooth Keyboard', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSANEXT16CF', 'name': u'SanDisk Extreme - 16GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANPRO16SD', 'name': u'SanDisk Extreme Pro - 16GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANPRO32CF', 'name': u'SanDisk Extreme Pro - 32GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANPRO64CF', 'name': u'SanDisk Extreme Pro - 64GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANULT04CF', 'name': u'SanDisk Ultra - 4GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANULT08CF', 'name': u'SanDisk Ultra - 8GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHMOTRAZB', 'name': u'Motorola Droid RAZR (Black)', 'weight': Decimal('0.310'), 'requires_serial_number': True},
            {'code': u'KHSGNEXB', 'name': u'Samsung Galaxy Nexus I9250 (16GB, Silver) - Unlocked', 'weight': Decimal('0.315'), 'requires_serial_number': True},
            {'code': u'KHNEWIPADWF16WHT', 'name': u'Apple New iPad (16GB, Wi Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHSONCSHX200VBLK', 'name': u'Sony Cyber-shot DSC-HX200V Digital Camera', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNEWIPADWF64WHT', 'name': u'Apple New iPad (64GB, Wi-Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCANBATGRPBGE9', 'name': u'Canon BG-E9 Battery Grip', 'weight': Decimal('0.750'), 'requires_serial_number': False},
            {'code': u'KHNEWIPAD4G16WHT', 'name': u'Apple New iPad (16GB, Mobile Broadband - Wi-Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNEWIPAD4G32WHT', 'name': u'Apple New iPad (32GB Mobile Broadband, Wi-Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNEWIPADWF64BLK', 'name': u'Apple New iPad (64GB, Wi-Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHHOYHDUV58', 'name': u'Hoya HD UV Filter - 58mm', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHBBDDSTUBLK', 'name': u'Beats by Dr. Dre - Studio (Black)', 'weight': Decimal('1.400'), 'requires_serial_number': True},
            {'code': u'KHNEWIPAD4G16BLK', 'name': u'Apple New iPad (16GB, Mobile Broadband, Wi-Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHNEWIPAD4G32BLK', 'name': u'Apple New iPad (32GB Mobile Broadband, Wi-Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHNEWIPADWF32WHT', 'name': u'Apple New iPad (32GB, Wi-Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNEWIPAD4G64BLK', 'name': u'Apple New iPad (64GB, Mobile Broadband, Wi-Fi - Black)', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHOLYEP3SLKBLK', 'name': u'Olympus PEN E-P3 Digital Camera with 14-42mm Lens (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGNOTEWHT', 'name': u'Samsung Galaxy Note N7000 (16GB, White) - Unlocked', 'weight': Decimal('0.358'), 'requires_serial_number': True},
            {'code': u'KHSANPRO08SD', 'name': u'SanDisk Extreme Pro - 8GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHNAFS50F14G', 'name': u'Nikon AF-S NIKKOR 50mm f/1.4G Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHCPSSX230HSB', 'name': u'Canon Powershot SX230 HS Compact Zoom Camera (Black)', 'weight': Decimal('1.223'), 'requires_serial_number': True},
            {'code': u'KHNK70300GEDVR', 'name': u'Nikon AF-S VR Zoom-Nikkor 70-300mm f/4.5-5.6G IF-ED Lens', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHSANEXT32CF', 'name': u'SanDisk Extreme - 32GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHNIKBATGRPMBD11', 'name': u'Nikon MB-D11 Battery Grip', 'weight': Decimal('0.800'), 'requires_serial_number': True},
            {'code': u'KHSANXHD04SD', 'name': u'SanDisk Extreme HD Video - 4GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSNEXC3K1855S', 'name': u'Sony NEX C3 Compact System Camera with 18-55mm Zoom Lens (Silver)', 'weight': Decimal('1.700'), 'requires_serial_number': True},
            {'code': u'KHNAFS50F18SL', 'name': u'Nikon AF-S NIKKOR 50mm F1.8G Standard Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHC1100DK18555-5250BLK', 'name': u'Canon EOS 1100D DSLR Camera Twin IS Lens Kit (Black)', 'weight': Decimal('2.300'), 'requires_serial_number': True},
            {'code': u'KHCANLPE6BATT', 'name': u'Canon LP-E6 Li-Ion Battery (Genuine)', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KH360CODMW3', 'name': u'Call of Duty: Modern Warfare 3 - Xbox 360 Game', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHIPAD32WWIFI', 'name': u'Apple iPad 2 - 32GB White with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD64B3G', 'name': u'Apple iPad 2 - 64GB Black with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHIPAD64BWIFI', 'name': u'Apple iPad 2 - 64GB Black with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKSB700FLS', 'name': u'Nikon Speedlight SB-700 Flash', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHNIKSB400FLS', 'name': u'Nikon Speedlight SB-400 Flash', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHSGTAB73GSLV', 'name': u'Samsung Galaxy Tab 7.7 3G 16GB (Silver) ', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGTAB7WIFISLV', 'name': u'Samsung Galaxy Tab 7.7 Wi-Fi 16GB (Silver)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KH11AIR064', 'name': u'Apple MacBook Air 11" 64GB SSD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCAN580EXFLS', 'name': u'Canon Speedlite 580EX II Flash', 'weight': Decimal('1.330'), 'requires_serial_number': True},
            {'code': u'KHCS43EX2F', 'name': u'Canon Speedlite 430EX II Flash', 'weight': Decimal('1.330'), 'requires_serial_number': True},
            {'code': u'KHSGNEXHONEYCSE', 'name': u'New Product KHSGNEXHONEYCSE', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHCANEF70300L', 'name': u'New Product KHCANEF70300L', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHIP2MAGCOVGRY', 'name': u'New Product KHIP2MAGCOVGRY', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHIP4S16WHT', 'name': u'Apple iPhone 4S 16GB (White)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHOYHDUV67', 'name': u'Hoya HD UV Filter - 67mm.', 'weight': Decimal('0.080'), 'requires_serial_number': True},
            {'code': u'KHCNN7D135KIT', 'name': u'Canon EOS 7D DSLR Camera Lens Kit with EF-S 18-135mm f/3.5-5.6 IS lens', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHCNN7DBODY', 'name': u'Canon EOS 7D DSLR Camera Body Only', 'weight': Decimal('1.820'), 'requires_serial_number': True},
            {'code': u'KHSONSMRTWTCHBLK', 'name': u'Sony SmartWatch (Black)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHSGS332WHT', 'name': u'Samsung Galaxy S3 I9300 (32GB, White) - Unlocked', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHNKND7000K105', 'name': u'Nikon D7000 DSLR 18-105mm Megazoom VR Kit', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KHCEFS55250ISL', 'name': u'Canon EF-S 55-250mm f/4-5.6 IS Telephoto Lens', 'weight': Decimal('0.720'), 'requires_serial_number': True},
            {'code': u'KHIP2MAGCOVBLU', 'name': u'New Product KHIP2MAGCOVBLU', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHCEF502SL', 'name': u'Canon EF 50mm f/1.8 II Standard Lens', 'weight': Decimal('0.460'), 'requires_serial_number': True},
            {'code': u'KHSONSLTA57BODY', 'name': u'Sony Alpha SLT-A57 DSLR Camera - Body', 'weight': Decimal('1.570'), 'requires_serial_number': True},
            {'code': u'KHCEFS55250F456ISTL', 'name': u'Canon EF-S 55-250mm F4-5.6 IS Telephoto Lens', 'weight': Decimal('0.720'), 'requires_serial_number': True},
            {'code': u'KHCEFS1022UZL', 'name': u'Canon EF-S 10-22mm USM Zoom Lens', 'weight': Decimal('0.715'), 'requires_serial_number': True},
            {'code': u'KHSONSLTA5718-55KIT', 'name': u'Sony Alpha SLT A57 18-55mm Lens Kit (A57K)', 'weight': Decimal('1.775'), 'requires_serial_number': True},
            {'code': u'KHCEFS1855F3556ISII', 'name': u'Canon EF-S 18-55mm f/3.5-5.6 IS II Lens', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHMXM103G', 'name': u'Motorola Xoom 10" - 32GB WiFi 3G Tablet (Silver)', 'weight': Decimal('1.330'), 'requires_serial_number': True},
            {'code': u'KHNAF50F18DSL', 'name': u'Nikon AF NIKKOR 50mm F1.8D Standard Lens', 'weight': Decimal('0.485'), 'requires_serial_number': True},
            {'code': u'KHNAFS18200VR2ZL', 'name': u'Nikon AF-S DX NIKKOR 18-200mm f/3.5-5.6G ED VR II Zoom Lens', 'weight': Decimal('0.890'), 'requires_serial_number': True},
            {'code': u'KHC60DB', 'name': u'Canon EOS 60D DSLR Camera - Body Only', 'weight': Decimal('1.755'), 'requires_serial_number': True},
            {'code': u'KHNK55300GEDVR', 'name': u'Nikon AF-S DX Nikkor 55-300mm f/4.5-5.6 G ED VR Lens', 'weight': Decimal('0.860'), 'requires_serial_number': True},
            {'code': u'KHNOKN9BU', 'name': u'Nokia N9 - 16GB (Blue)', 'weight': Decimal('0.315'), 'requires_serial_number': True},
            {'code': u'KHIPAD16BWIFI', 'name': u'Apple iPad 2 - 16GB Black with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNKND7000BODY', 'name': u'Nikon D7000 DSLR Body Only', 'weight': Decimal('1.780'), 'requires_serial_number': True},
            {'code': u'KHCEFS1855F3556SL', 'name': u'Canon EF-S 18-55mm f/3.5-5.6 IS Lens', 'weight': Decimal('0.530'), 'requires_serial_number': True},
            {'code': u'KHCEFS60F28UML', 'name': u'Canon EF-S 60mm F2.8 Macro USM Lens', 'weight': Decimal('0.665'), 'requires_serial_number': True},
            {'code': u'KHCNN5DMARKII105KIT', 'name': u'Canon EOS 5D Mark II DSLR Camera Lens Kit with EF 24-105mm F4.0L IS USM Lens', 'weight': Decimal('2.110'), 'requires_serial_number': True},
            {'code': u'KHIPAD16W3G', 'name': u'Apple iPad 2 - 16GB White with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHIP2MAGCOVBLK', 'name': u'iPad 2 Magnetic Cover (Black)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHIP2MAGCOVGRN', 'name': u'iPad 2 Magnetic Cover (Green)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHIP2MAGCOVPNK', 'name': u'iPad 2 Magnetic Cover (Pink)', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHIPAD16WWIFI', 'name': u'Apple iPad 2 - 16GB White with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNID90DK1855', 'name': u'Nikon D90 DSLR Camera Lens Kit with 18-105mm VR Lens', 'weight': Decimal('2.123'), 'requires_serial_number': True},
            {'code': u'KHNJ110B', 'name': u'Nikon 1 J1 with 10mm f/2.8 NIKKOR Lens (Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNOKL800B', 'name': u'Nokia Lumia 800 (Blue)', 'weight': Decimal('0.322'), 'requires_serial_number': True},
            {'code': u'KHNOKN9BL', 'name': u'Nokia N9 - 64GB (Black)', 'weight': Decimal('0.315'), 'requires_serial_number': True},
            {'code': u'KHNV1103030110W', 'name': u'Nikon 1 V1 with 10-30mm f/3.5-5.6 & 30-110mm f/3.8-5.6 NIKKOR Lenses (White)', 'weight': Decimal('1.700'), 'requires_serial_number': True},
            {'code': u'KHROCCARCRDL', 'name': u'iPhone Car Cradle', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHROCMODCASEG', 'name': u'Modular iPhone Case (Green)', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHIP4S32BLK', 'name': u'Apple iPhone 4S 32GB (Black)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHIP4S32WHT', 'name': u'Apple iPhone 4S 32GB (White)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHROCSIICASEHCBLK', 'name': u'Galaxy S II Honeycomb Case', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHSGNOTEB', 'name': u'Samsung Galaxy Note N7000 (16GB, Blue) - Unlocked', 'weight': Decimal('0.358'), 'requires_serial_number': True},
            {'code': u'KHCANBATGRPBGE6', 'name': u'Canon BG-E6 Battery Grip', 'weight': Decimal('0.750'), 'requires_serial_number': False},
            {'code': u'KAMBAS11I18I5256', 'name': u'Apple MacBook Air 13" - 1.8GHz i5 256GB MD232', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KAMBAS11I18I5128', 'name': u'Apple MacBook Air 13" - 1.8GHz i5 128GB MD 231', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCAN650D18-55-55-250KIT', 'name': u'Canon EOS 650D DSLR 18-55mm & 55-250mm IS II Lens Kit', 'weight': Decimal('2.400'), 'requires_serial_number': True},
            {'code': u'KAMBPS13I29I7', 'name': u'Apple MacBook Pro 13" - 2.9GHz i7 MD102', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KAMBPR15I26I7', 'name': u'Apple MacBook Pro 15" with Retina Display - 2.6GHz i7 MC976', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KHHTCSENXEWHT', 'name': u'HTC Sensation XE - Unlocked (White) (No Beats)', 'weight': Decimal('0.700'), 'requires_serial_number': True},
            {'code': u'KHC550DK1855-55250', 'name': u'Canon EOS 550D DSLR Camera Twin IS Lens Kit', 'weight': Decimal('2.030'), 'requires_serial_number': True},
            {'code': u'KHNIKJ11030WHT', 'name': u'Nikon 1 J1 with 10-30mm Lens (White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCAN600EXRTFLSH', 'name': u'Canon Speedlite 600EX-RT Flash', 'weight': Decimal('0.500'), 'requires_serial_number': True},
            {'code': u'KHNEWIPAD4G64WHT', 'name': u'Apple New iPad (64GB, Mobile Broadband, Wi-Fi - White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHHOYHDUV67', 'name': u'Hoya HD UV Filter - 67mm', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHSGS316WHTFBS', 'name': u'New Product KHSGS316WHTFBS', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHPANGX1X1442SLV', 'name': u'Panasonic Lumix DMC-GX1X 14-42mm Lens Kit (Silver)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHBBDDSHDBLK', 'name': u'Beats by Dr. Dre - Solo HD (Black)', 'weight': Decimal('1.400'), 'requires_serial_number': True},
            {'code': u'KHIPAD32B3G', 'name': u'Apple iPad 2 - 32GB Black with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHIP4S16BLK', 'name': u'Apple iPhone 4S 16GB (Black)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHSGS316BLU', 'name': u'Samsung Galaxy S3 I9300 (16GB, Blue) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHC1100DBBLK', 'name': u'Canon EOS 1100D DSLR Camera - Body Only (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHIPAD32BWIFI', 'name': u'Apple iPad 2 - 32GB Black with WiFi', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCEF73F456IUZL', 'name': u'Canon EF 70-300mm F4-5.6 IS USM Zoom Lens', 'weight': Decimal('0.960'), 'requires_serial_number': True},
            {'code': u'KHIPAD32W3G', 'name': u'Apple iPad 2 - 32GB White with 3G + WiFi', 'weight': Decimal('1.210'), 'requires_serial_number': True},
            {'code': u'KHC600DB', 'name': u'Canon EOS 600D DSLR Camera - Body Only', 'weight': Decimal('1.570'), 'requires_serial_number': True},
            {'code': u'KHNID5100DB', 'name': u'Nikon D5100 DSLR Camera - Body Only', 'weight': Decimal('1.510'), 'requires_serial_number': True},
            {'code': u'KHC1100DK1855BLK', 'name': u'Canon EOS 1100D DSLR Camera Lens Kit with 18-55mm f/3.5-5.6 IS II Lens (Black)', 'weight': Decimal('1.700'), 'requires_serial_number': True},
            {'code': u'KHHTCEVOB', 'name': u'HTC EVO 3D (Black)', 'weight': Decimal('0.350'), 'requires_serial_number': True},
            {'code': u'KHSANULT16CF', 'name': u'SanDisk Ultra - 16GB CF Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANXHD08SD', 'name': u'SanDisk Extreme HD Video - 8GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANXHD16SD', 'name': u'SanDisk Extreme HD Video - 16GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSANXHD32SD', 'name': u'SanDisk Extreme HD Video - 32GB SDHC Card', 'weight': Decimal('0.030'), 'requires_serial_number': False},
            {'code': u'KHSENCX310', 'name': u'Sennheiser CX 310 In-Ear Earphones', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHMBAS11I17I5064', 'name': u'Apple MacBook Air 11" - 1.7GHz i5 64GB MD223', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHHTCONEXGREY', 'name': u'HTC One X - Unlocked (Grey) 32GB', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHSAMGALNEX', 'name': u'New Product KHSAMGALNEX', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHIP4S64BLK', 'name': u'Apple iPhone 4S 64GB (Black)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHIP4S64WHT', 'name': u'Apple iPhone 4S 64GB (White)', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHSONSLTA5718-55-55-200KIT', 'name': u'Sony Alpha SLT-A57 18-55mm & 55-200 Lens Kit (A57Y)', 'weight': Decimal('2.500'), 'requires_serial_number': True},
            {'code': u'KHATPRIMEGLD', 'name': u'Asus Transformer Prime', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHNIKP7000BLK', 'name': u'Nikon Coolpix P7000 Digital Camera', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHHTCONEXLWHT', 'name': u'HTC One XL - Unlocked (White)', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHSGS332BLU', 'name': u'Samsung Galaxy S3 I9300 (32GB, Blue) - Unlocked', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHHTCONEXWHITE', 'name': u'HTC One X - Unlocked (White) 32GB', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHHTCONEVGREY', 'name': u'HTC One V - Unlocked (Grey)', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHHTCONEVBLACK', 'name': u'HTC One V - Unlocked (Black)', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHNIKENEL15BATT', 'name': u'Nikon EN-EL15 Li-Ion Battery (Genuine)', 'weight': Decimal('0.200'), 'requires_serial_number': False},
            {'code': u'KHPS3BTLFLD3', 'name': u'Battlefield 3 - PS3 Game', 'weight': Decimal('0.200'), 'requires_serial_number': False},
            {'code': u'KHPS3CODMW3', 'name': u'Call of Duty: Modern Warfare 3 - PS3 Game', 'weight': Decimal('0.100'), 'requires_serial_number': False},
            {'code': u'KHBRAUN720S', 'name': u'Braun Series 7 720s Electric Shaver', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCKISSX5K1855', 'name': u'Canon EOS Kiss X5 (600D) DSLR Camera Lens Kit with EF-S 18-55mm IS Lens', 'weight': Decimal('1.770'), 'requires_serial_number': True},
            {'code': u'KHCKISSX4DK1855', 'name': u'Canon EOS Kiss X4 (550D) DSLR 18-55mm IS Lens Kit', 'weight': Decimal('1.530'), 'requires_serial_number': True},
            {'code': u'KHSGS316WHT', 'name': u'Samsung Galaxy S3 I9300 (16GB, White) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHASUSTF300TBLU', 'name': u'Asus Transformer Pad (Wi-Fi, Blue) - TF300T - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCAN650D18-55KIT', 'name': u'Canon EOS 650D DSLR 18-55mm IS II Lens Kit', 'weight': Decimal('1.770'), 'requires_serial_number': True},
            {'code': u'KHNID5100DK1855', 'name': u'Nikon D5100 DSLR Camera Lens Kit with AF-S 18-55mm f3.5-5.6 G VR Lens', 'weight': Decimal('1.775'), 'requires_serial_number': True},
            {'code': u'KHSONRX100BLK', 'name': u'Sony Cyber-shot DSC-RX100 Digital Camera', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KAMBPS15I23I7', 'name': u'Apple MacBook Pro 15" - 2.3GHz i7 MD103', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KAMBPS15I26I7', 'name': u'Apple MacBook Pro 15" - 2.6GHz i7 MD104', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ11030BLK', 'name': u'Nikon 1 J1 with 10-30mm Lens (Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KAMBPS13I25I5', 'name': u'Apple MacBook Pro 13" - 2.5GHz i5 MD101', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KAMBPR15I23I7', 'name': u'Apple MacBook Pro 15" with Retina Display - 2.3GHz i7 MC975', 'weight': Decimal('2.200'), 'requires_serial_number': True},
            {'code': u'KHASUSTF300TKBBLU', 'name': u'Asus Transformer Pad and Keyboard TF300T (Wi-Fi, Blue)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGTAB28GB7', 'name': u'Samsung Galaxy Tab 2 (II) (7.0) 8GB Wi-Fi - Silver P3110 ', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHFUJX100BLK', 'name': u'Fujifilm FinePix X100 (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKJ11030SLV', 'name': u'Nikon 1 J1 with 10-30mm Lens (Silver)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHHTCSENB', 'name': u'New Product KHHTCSENB', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHC550DB', 'name': u'Canon EOS 550D DSLR Camera - Body Only', 'weight': Decimal('1.530'), 'requires_serial_number': True},
            {'code': u'KHNIKJ11030RED', 'name': u'Nikon 1 J1 with 10-30mm Lens (Red)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCANBATGRPBGE7', 'name': u'Canon BG-E7 Battery Grip', 'weight': Decimal('0.750'), 'requires_serial_number': False},
            {'code': u'KAOLYOMDBDYSLV', 'name': u'Olympus OM-D E-M5 Body - (Silver)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHSENCXC700', 'name': u'Sennheiser CXC 700 In-Ear Earphones', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KAMBAS11I17I5128', 'name': u'Apple MacBook Air 11" - 1.7GHz i5 128GB MD224', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCKISSX5K1855-55250', 'name': u'Canon EOS Kiss X5 (600D) DSLR Camera Twin IS Lens Kit 18-55mm & 55-250mm', 'weight': Decimal('1.900'), 'requires_serial_number': True},
            {'code': u'KHPANGX1X1442BLK', 'name': u'Panasonic Lumix DMC-GX1X 14-42mm Lens Kit (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSENIE80', 'name': u'Sennheiser IE 80 In-Ear Earphones', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHSAMGALSIIW', 'name': u'Samsung Galaxy S2 I9100 (16GB, White) - Unlocked', 'weight': Decimal('0.296'), 'requires_serial_number': True},
            {'code': u'KHSAMGALSII', 'name': u'Samsung Galaxy S2 I9100 (16GB, Black) - Unlocked', 'weight': Decimal('0.296'), 'requires_serial_number': True},
            {'code': u'KAOLYOMDBDYBLK', 'name': u'Olympus OM-D E-M5 Body - (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KAUSBXXADPA', 'name': u'USB Power Adapter', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHCANEF28135IS', 'name': u'Canon EF 28-135mm F3.5-5.6 IS USM Lens', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHNIKAFS18105GED', 'name': u'Nikon AF-S DX NIKKOR 18-105mm F3.5-5.6G ED VR', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'NIKAFSDX40G', 'name': u'Nikon AF-S DX Micro NIKKOR 40mm F2.8G Lens', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHHDHERO2SE', 'name': u'GoPro HD HERO2: Surf Edition', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHHDHERO2OE', 'name': u'GoPro HD HERO2: Outdoor Edition', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHHDHERO2MSE', 'name': u'GoPro HD HERO2: Motorsports Edition', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHLED32XXXYBP', 'name': u'New Product KHLED32XXXYBP', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHSGN101WFWHT', 'name': u'Samsung Galaxy Note 10.1 N8010 (White, Wi-Fi, 16GB)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHBRAUN760CC', 'name': u'Braun Series 7 760cc Electric Shaver', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNEXUS78GB', 'name': u'Google Nexus 7 (8GB)', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHNEXUS716GB', 'name': u'Google Nexus 7 (16GB)', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHCANEFS18200IS', 'name': u'Canon EF-S 18-200mm F3.5-5.6 IS Standard Zoom Lens', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHCANEF35WL', 'name': u'Canon EF 35mm F2 Wide Angle Lens', 'weight': Decimal('0.300'), 'requires_serial_number': True},
            {'code': u'KHBLUTTHKBCVR', 'name': u'Bluetooth Keyboard & Case for iPad 2', 'weight': Decimal('1.000'), 'requires_serial_number': False},
            {'code': u'KHNID5100DK185555300', 'name': u'Nikon D5100 DSLR Camera Twin VR Lens Kit with 18-55mm f3.5-5.6 G VR Lens & AF-S 55-300mm f4.5-5.6 G VR Lens', 'weight': Decimal('2.500'), 'requires_serial_number': True},
            {'code': u'KHNAFS1855F3556', 'name': u'Nikon AF-S DX NIKKOR 18-55mm f3.5-5.6 G VR Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHCNN5DMARKIIBODY', 'name': u'Canon EOS 5D Mark II DSLR Body Only', 'weight': Decimal('1.810'), 'requires_serial_number': True},
            {'code': u'KHNJ1103030110W', 'name': u'Nikon 1 J1 with 10-30mm f/3.5-5.6 & 30-110mm f/3.8-5.6 NIKKOR Lenses (White)', 'weight': Decimal('1.700'), 'requires_serial_number': True},
            {'code': u'KHCKISSX4K1855-55250', 'name': u'Canon EOS Kiss X4 (550D) DSLR Camera Twin IS Lens Kit', 'weight': Decimal('2.030'), 'requires_serial_number': True},
            {'code': u'KHC550DK1855', 'name': u'Canon EOS 550D DSLR Camera Lens Kit with EF-S 18-55mm f3.5-5.6 IS Lens', 'weight': Decimal('1.730'), 'requires_serial_number': True},
            {'code': u'KHSGN1013GWHT', 'name': u'Samsung Galaxy Note 10.1 N8000 (White, 3G, 16GB) - Unlocked', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHSGN1013GGRY', 'name': u'Samsung Galaxy Note 10.1 N8000 (Grey, 3G, 16GB) - Unlocked', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHTF700T32GRY', 'name': u'ASUS Transformer Pad Infinity TF700T (32GB, Wi-Fi, Grey) - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHOLYOMDBDYSLV', 'name': u'Olympus OM-D E-M5 Body (Silver)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHCANEFS18135IS', 'name': u'Canon EF-S 18-135mm F3.5-5.6 IS Standard Zoom Lens', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHSGN101WFGRY', 'name': u'Samsung Galaxy Note 10.1 N8010 (Grey, Wi-Fi, 16GB)', 'weight': Decimal('1.165'), 'requires_serial_number': True},
            {'code': u'KHNIKP7100BLK', 'name': u'Nikon Coolpix P7100 Digital Camera (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKS9300SLV', 'name': u'Nikon Coolpix S9300 Digital Camera (Silver)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHSP3PKSGNA', 'name': u'Screen Protector for Samsung Galaxy Note - 3 Pack', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSPXXXSGNA', 'name': u'Screen Protector for Samsung Galaxy Note', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSGNOTEIIGRY', 'name': u'Samsung Galaxy Note 2 N7100 (16GB, Grey) - Unlocked', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHSGNOTEIIWHT', 'name': u'Samsung Galaxy Note 2 N7100 (16GB, White) - Unlocked', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHIP408BLK', 'name': u'Apple iPhone 4 (8GB, Black) - Unlocked', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHIP408WHT', 'name': u'Apple iPhone 4 (8GB, White) - Unlocked', 'weight': Decimal('0.400'), 'requires_serial_number': True},
            {'code': u'KHBOSEOE2BLK', 'name': u'Bose OE2 Audio Headphones (Black)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHBOSEOE2WHT', 'name': u'Bose OE2 Audio Headphones (White)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHCANS110BLK', 'name': u'Canon Powershot S110 (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHPS3SLM320BLK', 'name': u'Sony PS3 (Slim, 320GB, Black)', 'weight': Decimal('5.000'), 'requires_serial_number': True},
            {'code': u'KHPS3FIFA12', 'name': u'FIFA 12 - PS3 Game', 'weight': Decimal('0.080'), 'requires_serial_number': False},
            {'code': u'KHSENHD650', 'name': u'Sennheiser HD 650 Headphones', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHSENHD558', 'name': u'Sennheiser HD 558 Headphones', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHCANEF40STM', 'name': u'Canon EF 40mm F2.8 STM Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHCANEF85USM', 'name': u'Canon EF 85mm F1.8 USM Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHTBXP500BLK', 'name': u'Turtle Beach Ear Force XP500 Gaming Headset', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHGF5X1442BLK', 'name': u'Panasonic Lumix DMC-GF5X 14-42mm Lens Kit (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHGF5X1442WHT', 'name': u'Panasonic Lumix DMC-GF5X 14-42mm Lens Kit (White)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHASUSTF300TWHT', 'name': u'Asus Transformer Pad TF300T (Wi-Fi, White) - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHSGS34G16BLK', 'name': u'Samsung Galaxy S3 4G i9305 (16GB, Black) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHSGS34G16GRY', 'name': u'Samsung Galaxy S3 4G i9305 (16GB, Grey) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHSGS316RED', 'name': u'Samsung Galaxy S3 I9300 (16GB, Red) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHNIKAW100BLK', 'name': u'Nikon Coolpix AW100 Digital Camera (Black)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHNIKAW100ORG', 'name': u'Nikon Coolpix AW100 Digital Camera (Orange)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHNIKAW100BLU', 'name': u'Nikon Coolpix AW100 Digital Camera (Blue)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHOLYOMDBDYBLK', 'name': u'Olympus OM-D E-M5 Body (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KADOKMMSG3A', 'name': u'New Product KADOKMMSG3A', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHTF700T64GRY', 'name': u'ASUS Transformer Pad Infinity TF700T (64GB, Wi-Fi, Grey) - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHBOSEOE2IBLK', 'name': u'Bose OE2i Audio Headphones (Black)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHBOSEOE2IWHT', 'name': u'Bose OE2i Audio Headphones (White)', 'weight': Decimal('0.200'), 'requires_serial_number': True},
            {'code': u'KHSPXXXGS2A', 'name': u'Screen Protector for Samsung Galaxy S2', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSPXXXGS3A', 'name': u'Screen Protector for Samsung Galaxy S3', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSP3PKGS3A', 'name': u'Screen Protector for Samsung Galaxy S3 - 3 Pack', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHSGTAB216GB10', 'name': u'Samsung Galaxy Tab 2 (II) (10.1) 16GB Wi-Fi - Silver P5110 ', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHASUSTF300TKBWHT', 'name': u'Asus Transformer Pad and Keyboard TF300T (Wi-Fi, White)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHPS3SLM160BLK', 'name': u'Sony PS3 (Slim, 160GB, Black)', 'weight': Decimal('5.000'), 'requires_serial_number': True},
            {'code': u'KHSP3PKGN2A', 'name': u'Screen Protector for Samsung Galaxy Note 2 - 3 Pack', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHRQ1280CC', 'name': u'Philips SensoTouch 3D RQ1280CC', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHRQ1290CC', 'name': u'Philips SensoTouch 3D RQ1290CC', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030ORG', 'name': u'Nikon 1 J2 10-30mm Lens (Orange)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030WHT', 'name': u'Nikon 1 J2 10-30mm Lens (White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030PNK', 'name': u'Nikon 1 J2 10-30mm Lens (Pink)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030RED', 'name': u'Nikon 1 J2 10-30mm Lens (Red)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030BLK', 'name': u'Nikon 1 J2 10-30mm Lens (Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030SLV', 'name': u'Nikon 1 J2 10-30mm Lens (Silver)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KAROCS3CASEHCBLK', 'name': u'New Product KAROCS3CASEHCBLK', 'weight': Decimal('0.000'), 'requires_serial_number': True},
            {'code': u'KHFUJX10BLK', 'name': u'Fujifilm X10 Digital Camera (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHTF700T32GLD', 'name': u'ASUS Transformer Pad Infinity TF700T (32GB, Wi-Fi, Gold) - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'BRAUN790CC', 'name': u'Braun Series 7 790cc Electric Shaver', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCANEOSM1855', 'name': u'Canon EOS M Digital Camera with 18-55mm IS STM Lens', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHTF700T64GLD', 'name': u'ASUS Transformer Pad Infinity TF700T (64GB, Wi-Fi, Gold) - NO KEYBOARD', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHCANEOSM22MA', 'name': u'Canon EOS M Digital Camera with 22mm STM Lens & EF-EOS Mount Adapter', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGNOTEII4GWHT', 'name': u'Samsung Galaxy Note 2 4G N7105 (16GB, White) - Unlocked', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHCANPSG15', 'name': u'Canon Powershot G15', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110WHT', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (White)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110SLV', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (Silver)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110RED', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (Red)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110PNK', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (Pink)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110ORG', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (Orange)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHNIKJ21030-30110BLK', 'name': u'Nikon 1 J2 with 10-30mm & 30-110mm Lens (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGNOTEII4GGRY', 'name': u'Samsung Galaxy Note 2 4G N7105 (16GB, Grey) - Unlocked', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHLYTRO16GBRED', 'name': u'Lytro Light Field Camera (16GB, Red)', 'weight': Decimal('0.500'), 'requires_serial_number': True},
            {'code': u'KHLYTRO8GBGRY', 'name': u'Lytro Light Field Camera (8GB, Grey)', 'weight': Decimal('0.500'), 'requires_serial_number': True},
            {'code': u'KHLYTRO8GBBLU', 'name': u'Lytro Light Field Camera (8GB, Blue)', 'weight': Decimal('0.500'), 'requires_serial_number': True},
            {'code': u'KHNIKS800CBLK', 'name': u'Nikon Coolpix S800c (Black)', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHNIKS800CWHT', 'name': u'Nikon Coolpix S800c (White)', 'weight': Decimal('1.000'), 'requires_serial_number': True},
            {'code': u'KHNOKLM90016BLU', 'name': u'Nokia Lumia 900 (16GB, Blue) - Unlocked', 'weight': Decimal('0.322'), 'requires_serial_number': True},
            {'code': u'KHPS3SSLM500BLK', 'name': u'Sony PS3 Super Slim (500GB, Black)', 'weight': Decimal('3.400'), 'requires_serial_number': True},
            {'code': u'KHPS3SSLM250BLK', 'name': u'Sony PS3 Super Slim (250GB, Black)', 'weight': Decimal('3.400'), 'requires_serial_number': True},
            {'code': u'KHFUJXE1SLV', 'name': u'Fujifilm X-E1 Body Only (Silver)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KHFUJXE1BLK', 'name': u'Fujifilm X-E1 Body Only (Black)', 'weight': Decimal('0.900'), 'requires_serial_number': True},
            {'code': u'KAFUJXE135SLV', 'name': u'Fujifilm X-E1 with XF 35mm F1.4 R Kit (Silver)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KAFUJXE135BLK', 'name': u'Fujifilm X-E1 with XF 35mm F1.4 R Kit (Black)', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHSGS316BLK', 'name': u'Samsung Galaxy S3 I9300 (16GB, Black) - Unlocked', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHNOKLUMIA800BLU', 'name': u'Nokia Lumia 800 (16GB, Blue)', 'weight': Decimal('0.250'), 'requires_serial_number': True},
            {'code': u'KHCAN650D18135KIT', 'name': u'Canon EOS 650D DSLR 18-135mm IS STM Lens Kit', 'weight': Decimal('1.500'), 'requires_serial_number': True},
            {'code': u'KHBRAUN790CC', 'name': u'Braun Series 7-790cc Electric Shaver', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD416WWHT', 'name': u'Apple iPad 4 with Retina Display (16GB, Wi-Fi, White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD432WBLK', 'name': u'Apple iPad 4 with Retina Display (32GB, Wi-Fi, Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD432WWHT', 'name': u'Apple iPad 4 with Retina Display (32GB, Wi-Fi, White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD464WBLK', 'name': u'Apple iPad 4 with Retina Display (64GB, Wi-Fi, Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD464WWHT', 'name': u'Apple iPad 4 with Retina Display (64GB, Wi-Fi, White)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHIPAD416WBLK', 'name': u'Apple iPad 4 with Retina Display (16GB, Wi-Fi, Black)', 'weight': Decimal('1.200'), 'requires_serial_number': True},
            {'code': u'KHSPXXXGN2A', 'name': u'Screen Protector for Samsung Galaxy Note 2', 'weight': Decimal('0.000'), 'requires_serial_number': False},
            {'code': u'KHNEXUS732GB', 'name': u'Google Nexus 7 (32GB)', 'weight': Decimal('0.750'), 'requires_serial_number': True},
            {'code': u'KHCANEFS1855', 'name': u'Canon EF-S 18-55mm F3.5-5.6 IS II Lens', 'weight': Decimal('0.450'), 'requires_serial_number': True},
            {'code': u'KHCANEOSMFKIT', 'name': u'Canon EOS M Digital Camera with 18-55mm, 22mm Lenses & 90EX Flash', 'weight': Decimal('1.500'), 'requires_serial_number': True},
        ]


        def install_suppliers():
            '''
            Load suppliers from the established list
            '''
            print 'Installing Suppliers'
            for _supplier in supplier_list:
                print _supplier
                print _supplier.get('name')
                if _supplier.get('name') and _supplier.get('email') and _supplier.get('colour'):
                    supplier, created = get_model('suppliers', 'Supplier').objects.get_or_create(
                            name__iexact = _supplier.get('name'),
                            defaults = {
                                'name': _supplier.get('name').upper(),
                                'email': _supplier.get('email'),
                                'colour': _supplier.get('colour'),
                            }
                        )
                    if created:
                        print 'Created Supplier %s' % str(supplier.pk)
                    else:
                        print 'Found Supplier %s' % str(supplier.pk)


        def install_products():
            '''
            Installs products from the list above

            This will also automatically create supplier products
            using the post_save signal issued by the Product
            model in Allocate
            '''
            print 'Installing Products'
            for _product in product_list:
                print _product
                product, created = get_model('products', 'Product').objects.get_or_create(
                        code__iexact = _product.get('code'),
                        defaults = {
                            'code': _product.get('code').upper(),
                            'name': _product.get('name'),
                            'weight': _product.get('weight'),
                            'requires_serial_number': _product.get('requires_serial_number'),
                        }
                    )
                if created:
                    print 'Created Product %s' % str(product.pk)
                else:
                    print 'Found Product %s' % str(product.pk)
                    product.weight = _product.get('weight')
                    product.requires_serial_number = _product.get('requires_serial_number')
                    product.name = _product.get('name')
                    product.save()


        install_products()
        install_suppliers()